version: "3"
services:
    python-app:
        build: .
        ports:
            - "80:8000"
        depends_on:
            - postgres
        
    postgres:
        image: postgres
        restart: "always"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: hw_02
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 567234
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080